# Generated by Django 3.2.7 on 2021-11-08 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reatapiapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emp_id',
        ),
    ]
